IATI/ckanext-iati

- ckanext/iati/theme/templates/home/index.html
@amercader any chance to push the to staging, so I can review it (and work on subsequent pages)?
> First refresh of IATI Registry homepage

- ckanext/iati/theme/templates/header.html
Please review this code to confirm which is designed to add a banner to all pages on the IATI Registry. If all ok, please merge into the IATI extension and deploy to the site ASAP.
Once the upgrade is complete in October, this change can be reverted in order to remove the banner.
Many thanks,
Dale
IATI Developer
> Add banner to IATI Registry to inform users of upcoming upgrade

- ckanext/iati/theme/templates/header.html
Hello,
Could we merge and deploy this pull request on the IATI Registry site.
Many thanks,
Dale
IATI Developer
> Update banner message following CKAN upgrade to v2.5.2

- ckanext/iati/emailer.py
- ckanext/iati/theme/templates/header.html
- ckanext/iati/theme/templates/static/help.html
- ckanext/iati/theme/templates/static/registry-api.html
Hello,
Could we merge and deploy this pull request on the IATI Registry site.  This should resolve issue #98 .
Many thanks,
Dale
IATI Developer
> [#98] Change IATI Community links to Discuss

- ckanext/iati/logic/validators.py
Contrary to the documentation, `id` is required for updating or patching an organization via the API, so we can use that value when validating `publisher_iati_id` rather than `name` without changing the workflow for users of the API. Using `id` instead of `name` also allows `name` and `publisher_iati_id` to be changed independently of one another.
> [#128] Validate publisher_iati_id by id

- ckanext/iati/helpers.py
- ckanext/iati/plugins.py
- ckanext/iati/theme/templates/organization/index.html
- ckanext/iati/theme/templates/organization/snippets/organization_list_ids.html
> [#137] Iati org id feature

- README.rst
Add missing versions to IATI Standard Version
> Add supported IATI Standard Version

- ckanext/iati/theme/templates/organization/snippets/organization_list_ids.html
Refs https://github.com/ViderumGlobal/ckanext-iati/issues/137#issuecomment-338645645
> Make column heading singular

- ckanext/iati/helpers.py
- ckanext/iati/lists.py
- ckanext/iati/plugins.py
- ckanext/iati/tests/test_csv.py
- setup.py
This pull request removes several unused imports from various modules.
> Remove unused imports

- ckanext/iati/archiver.py
> Make archiver compare old hash with new hash

- ckanext/iati/helpers.py
- ckanext/iati/plugins.py
- ckanext/iati/theme/templates/header.html
- ckanext/iati/theme/templates/organization/snippets/organization_form.html
- ckanext/iati/theme/templates/snippets/organization.html
> Revert "Fix countries.xml names"

- ckanext/iati/theme/fanstatic_library/styles/iati.css
- ckanext/iati/theme/less/header.less
> Fetch logo over https to fix mixed content warning

- ckanext/iati/theme/templates/home/index.html
@PetyaKangalova @jahnvidave I've updated the wording on the Registry homepage, as well as some of the links. (https://github.com/IATI/ckanext-iati/issues/170)
Please can you review and suggested edits.
@derwas no action needed for the moment. We will review this internally first.
Thank you, Amy
> Update home page text

- ckanext/iati/theme/templates/organization/snippets/organization_form.html
- ckanext/iati/theme/templates/package/snippets/package_basic_fields.html
- ckanext/iati/theme/templates/static/help_csv-import.html
Clarify that the email address inputted here will be available to the public.
@PetyaKangalova please can you review and approve
@gtkChop please can you implement this change once the PR is merged.
> Update wording about contact email

- ckanext/iati/archiver.py
> Use a concise selector for counting activities

- ckanext/iati/theme/templates/header.html
Update header Community link from Discuss to IATI Connect https://iaticonnect.org
Github issue: https://github.com/IATI/ckanext-iati/issues/359
> Update header.html Community link

- ckanext/iati/theme/templates/csv/upload.html
Noted that the file size limit is missing from this page. Adding in to help users prepare their data effectively.
> Add in details of file size limit

- ckanext/iati/emailer.py
- ckanext/iati/logic/validators.py
Github issue: https://github.com/IATI/ckanext-iati/pull/415
> removing literal for publisher name and url

- ckanext/iati/theme/templates/user/new_user_and_publisher_form.html
- ckanext/iati/views/publisher.py
Captcha added for: https://staging.iatiregistry.org/register_publisher/
> adding hCaptcha for user and publisher create

- ckanext/iati/logic/csv_action.py
- ckanext/iati/theme/templates/organization/read.html
Fix for 
- https://github.com/IATI/ckanext-iati/issues/430
- https://github.com/IATI/ckanext-iati/issues/426
- https://github.com/IATI/ckanext-iati/issues/424
Tested on:
- https://staging.iatiregistry.org/publisher/download/csv
- https://staging.iatiregistry.org/csv/download/abaseen
- https://staging.iatiregistry.org/publisher/download/json
- https://iatiregistry.org/dashboard/recent-publishers/download
Also added:
https://github.com/IATI/ckanext-iati/issues/427
Test:
https://staging.iatiregistry.org/organization/asdb?country=Azerbaijan
> Fix downloads
